AdvertProject/Models/Advert.cs
using AdvertProject.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace ProjectAdvert.Models
{
    [OutputCache(NoStore = true, Duration = 0, Location = OutputCacheLocation.None)]
    public class Advert
    {
        [Key]
        public int ID { get; set; }

        [Display(Name = "Advert", ResourceType = typeof(Resources.Content))]
        [DataType(DataType.MultilineText)]
        [Required]
        [MaxLength(1500)]
        [AllowHtml]
      
        public string Content { get; set; }

        public string UserID { get; set; }
        public virtual ApplicationUser User { get; set; }

        [Display(Name = "Date", ResourceType = typeof(Resources.Content))]
        [DataType(DataType.Date)]
        public DateTime? Date { get; set; }

        [Display(Name = "Category", ResourceType = typeof(Resources.Content))]
        public ICollection<AdvertCategory> categories{ get; set; }

    }
}

AdvertProject/Controllers/AdvertsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Text;
using System.Web.Helpers;
using System.Web.Mvc;
using AdvertProject.Models;
using Microsoft.AspNet.Identity;
using ProjectAdvert.Models;
using System.Web.UI.WebControls;

using System.ServiceModel.Syndication;
using System.Data.Entity.Core.Objects;
using System.Web;
using Microsoft.Ajax.Utilities;

namespace AdvertProject.Controllers
{
    public class AdvertsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Filter()
        {
            ViewBag.Categories = new MultiSelectList(db.Categories, "ID", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult Filter(FormCollection form)
        {
            String categoriesIdsString = form["categories"];
            TempData["FilterCategories"] = categoriesIdsString;
            return RedirectToAction("Index");
        }

        // GET: Adverts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Advert advert = db.Adverts.Include(x => x.categories).FirstOrDefault(z => z.ID == id);
            if (advert == null)
            {
                return HttpNotFound();
            }
            // Licznik odwiedzin
            var app = HttpContext.Application;
            string advertId = advert.ID.ToString();
            var current = app[advertId];
            
            

            if (current == null)
                app[advertId] = 1;
            else
                app[advertId] = (int)current + 1;

            ViewBag.VisitCount = app[advertId];

            return View(advert);
        }

        // GET: Adverts/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.Categories = new MultiSelectList(db.Categories, "ID", "Name");

            return View();
        }

        private string HtmlTagValidate(string text)
        {
            List<int> openTagIndexes = Regex.Matches(text, "<").Cast<Match>().Select(m => m.Index).ToList();
            List<int> closeTagIndexes = Regex.Matches(text, ">").Cast<Match>().Select(m => m.Index).ToList();
            if (closeTagIndexes.Count <= 0)
            {
                return text;
            }

            StringBuilder sb = new StringBuilder();
            int previousIndex = 0;
            foreach (int closeTagIndex in closeTagIndexes)
            {

                var openTagsSubset = openTagIndexes.Where(x => x >= previousIndex && x < closeTagIndex);
                if (openTagsSubset.Count() <= 0 || closeTagIndex - openTagsSubset.Max() <= 1)
                {
                    sb.Append(text.Substring(previousIndex, closeTagIndex - previousIndex + 1));
                    previousIndex = closeTagIndex + 1;
                    continue;
                }

                bool allowed = false;
                int tagSize = 0;
                foreach (var allowedTag in db.HtmlTags.ToList())
                {
                    var testString = text.Substring(openTagsSubset.Max() + 1);
                    if (testString.StartsWith(allowedTag.Tag) || testString.StartsWith("/" + allowedTag.Tag))
                    {
                        allowed = true;
                        tagSize = allowedTag.Tag.Length;
                        sb.Append(text.Substring(previousIndex, closeTagIndex - previousIndex + 1));
                        break;
                    }
                }
                if (!allowed)
                {
                    sb.Append(text.Substring(previousIndex, openTagsSubset.Max() - previousIndex));
                }
                previousIndex = closeTagIndex + 1;
            }
            if (closeTagIndexes.Max() < text.Length)
            {
                sb.Append(text.Substring(closeTagIndexes.Max() + 1));
            }
            return sb.ToString();
        }

        //first version
        /*private string HtmlTagValidate(string content)
        {
            //Prepere list of possible begining of html tags
            List<int> indexes = new List<int>();
            for (int index = 0; ; index += 1)
            {
                index = content.IndexOf('<', index);
                if (index == -1)    //no more
                    break;
                if (index - 1 >= 0 && content[index - 1] == '\\') //check if escaped
                {
                    content.Remove(index - 1, index - 1); //remove escape sing
                    continue;
                }

                if (index + 1 < content.Length && content[index + 1] != '/')    //chcek if ending
                    indexes.Add(index);
            }

            int HtmlClear(int i)
            {
                var index = indexes[i];
                //two kinds of engings - small e.g <a ... />, big e.g <b>.... </b>
                int nearestSmall = content.IndexOf("/>", index);
                int nearestBig = content.IndexOf("</", index);
                int next;
                if (nearestSmall == -1 && nearestBig == -1)
                    return i;
                if (i + 1 < indexes.Count)
                    next = indexes[i + 1];
                else
                    next = -1;
                //check if allowed
                foreach (var allowedTag in db.HtmlTags.ToList())
                {
                    if (content.Substring(index + 1).StartsWith(allowedTag.Tag))
                    {
                        return i;
                    }
                }

                //check if something inside - recursive
                if (next > -1 && nearestSmall > next && nearestBig > next)
                    i = HtmlClear(i + 1);
               

                if (nearestSmall < next || (next == -1 && nearestSmall != -1))
                {
                    content = content.Remove(index, nearestSmall - index + 1);
                }
                else if (nearestBig < next || (next == -1 && nearestBig != -1))
                {
                    content = content.Remove(index, content.IndexOf(">", index) - index + 1);
                    nearestBig = content.IndexOf("</", index);
                    content = content.Remove(nearestBig, content.IndexOf(">", nearestBig) - nearestBig + 1);
                }
                return i;
            }

            for (int i = 0; i < indexes.Count; i++)
            {
                i = HtmlClear(i);
            }
            return content;

        }*/

        // GET: Adverts
        public ActionResult Index()
        {
            IQueryable<Advert> adverts = db.Adverts.Include(a => a.User);
            if (TempData["FilterCategories"] != null)
            {
                adverts = adverts.Where(x => 1 == 0);
                String categoriesIdsString = Convert.ToString(TempData["FilterCategories"]);
                List<string> choosesList = categoriesIdsString.Split(',').ToList();
                foreach (string category in choosesList)
                {
                    var advertsTmp = db.Adverts.Include(a => a.User);
                    var id = Int32.Parse(category);
                    var cat = db.Categories.Where(x => x.ID == id).FirstOrDefault();
                    advertsTmp = advertsTmp.Where(x => x.categories.Contains(db.AdvertCategories.Where(ac => ac.CategoryID == cat.ID).FirstOrDefault()));
                    adverts = adverts.Union(advertsTmp);
                    advertsTmp = db.Adverts.Include(a => a.User);
                    advertsTmp = advertsTmp.Where(x => x.categories.Contains(db.AdvertCategories.Where(ac => ac.Category.RootCategory.ID == cat.ID).FirstOrDefault()));
                    adverts = adverts.Union(advertsTmp);
                }
            }
            var app = HttpContext.Application;
            ViewData["app"] = app;

            return View(adverts.ToList());
        }

        private void UpdateRss()
        {
            var rssItems = new List<SyndicationItem>();

            var advertsContent = db.Adverts.Where(a => EntityFunctions.TruncateTime(a.Date) == EntityFunctions.TruncateTime(DateTime.Now)).AsNoTracking().ToList();
            advertsContent
                .ForEach(a => rssItems.Add(
                    new SyndicationItem(a.ID.ToString(), a.Content, new Uri(Request.Url.Scheme + "://" + Request.Url.Authority + "/Adverts/Details/" + a.ID.ToString())
                    )));
            var feed = new SyndicationFeed("Ogloszex", "Najnowsze ogloszenia na stronie Ogloszex", new Uri(Request.Url.Scheme + "://" + Request.Url.Authority + "/Rss"), "Rss feed id", DateTime.Now, rssItems);


            var app = HttpContext.Application;
            app["RssFeed"] = feed;
        }




        // POST: Adverts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Content,UserID,Date")] Advert advert)
        {
            if (ModelState.IsValid)
            {
                //Content validation in case of forbiden words
                List<ForbidenWord> forbidenWords = db.ForbidenWords.ToList();
                bool contentSafe = true;

                foreach (ForbidenWord f in forbidenWords)
                {
                    if (advert.Content.Contains(f.Content))
                    {
                        contentSafe = false;
                        ModelState.AddModelError("Content", "Ogłoszenie zawiera zakazane słowo: " + f.Content);
                        break;
                    }
                }

AdvertProject/Views/Adverts/Create.cshtml
@model ProjectAdvert.Models.Advert


@{
    ViewBag.Title = "Create";
}

<h2>@Resources.Content.Create</h2>


@using (Html.BeginForm("Create", "Adverts", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form_class", role = "form" }))
{
    @Html.AntiForgeryToken()

    <h4>@Resources.Content.Advert</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form_div">
        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label " })
        @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control field_class" } })
        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
    </div>


    <div class="form_div">
        
        @Html.LabelFor(model => model.categories,Resources.Content.Category, htmlAttributes: new { @class = "control-label" })
        @Html.DropDownList("categories", null, htmlAttributes: new { @class = "form-control field_class", multiple = "multiple" })
        @Html.ValidationMessageFor(model => model.categories, "", new { @class = "text-danger" })
    </div>

    <div class="form_div">
        

        <input type="submit" value=@Resources.Content.Create class="btn btn-default" />
    </div>

    <div class="info_div">
        @Html.ActionLink(@Resources.Content.Back, "Index")
    </div>
}

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

AdvertProject/Views/Adverts/Delete.cshtml
@model ProjectAdvert.Models.Advert

@{
    ViewBag.Title = "Delete";
}


<h3>@Resources.Content.DeleteQuestion</h3>
<div>
    <h4>>@Resources.Content.Advert</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value=@Resources.Content.Delete class="btn btn-default" /> |
            @Html.ActionLink(@Resources.Content.Back, "Index", null, new { @Class = "btn btn-default" })
        </div>
    }
</div>

AdvertProject/Views/Adverts/Details.cshtml
@model ProjectAdvert.Models.Advert

@{
    ViewBag.Title = "Details";
}

<div>
    <h4>@Resources.Content.Advert</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd class="ddContent">
            @Html.Raw(Model.Content)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.categories)
        </dt>
        <dd>
            @if (Model.categories.Count>0) {
                foreach (var category in Model.categories)
                {
                <div>@category.Category.Name </div> 
                }
            }
            else
            {
                <div>...</div>
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink(@Resources.Content.Edit, "Edit", new { id = Model.ID }, new { @Class = "btn btn-default" }) |
    @Html.ActionLink(@Resources.Content.Back, "Index", null, new { @Class = "btn btn-default" })
</p>

AdvertProject/Views/Adverts/Edit.cshtml
@model ProjectAdvert.Models.Advert

@{
    ViewBag.Title = "Edit";
}

<h2>@Resources.Content.Edit</h2>


@using (Html.BeginForm("Edit", "Adverts", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form_class", role = "form" }))
{
    @Html.AntiForgeryToken()

    <h4>@Resources.Content.Advert</h4>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID)
    @Html.HiddenFor(model => model.User)
    @Html.HiddenFor(model => model.UserID)
    @Html.HiddenFor(model => model.Date)
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form_div">

        @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label " })
        @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control field_class" } })
        @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
    </div>


    <div class="form_div">

        @Html.LabelFor(model => model.categories, "Kategorie", htmlAttributes: new { @class = "control-label" })
        @Html.DropDownList("categories", null, htmlAttributes: new { @class = "form-control field_class", multiple = "multiple" })
        @Html.ValidationMessageFor(model => model.categories, "", new { @class = "text-danger" })
    </div>

    <div class="form_div">


        <input type="submit" value=@Resources.Content.Create class="btn btn-default" />
    </div>

    <div class="info_div">
        @Html.ActionLink(@Resources.Content.Back, "Index")
    </div>
}

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

AdvertProject/Views/Adverts/Filter.cshtml
@model ProjectAdvert.Models.Advert
@{
    ViewBag.Title = "Filter";
}



@using (Html.BeginForm("Filter", "Adverts", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form_class", role = "form" }))
{
    @Html.AntiForgeryToken()

<div class="form_div">

    @Html.LabelFor(model => model.categories, @Resources.Content.Category, htmlAttributes: new { @class = "control-label" })
    @Html.DropDownList("categories", null, htmlAttributes: new { @class = "form-control field_class", multiple = "multiple" })
</div>

    <div class="form_div">
        <input type="submit" value=@Resources.Content.Filter class="btn btn-default" />
    </div>

    <div class="info_div">
        @Html.ActionLink(@Resources.Content.Back, "Index")
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AdvertProject/Views/Adverts/Index.cshtml
@model IEnumerable<ProjectAdvert.Models.Advert>

@{
    ViewBag.Title = "Index";
}

@Styles.Render("~/Content/Site.css")

<p style= "margin-top:25px">
    @Html.ActionLink(@Resources.Content.Filter, "Filter", null, new {@Class = "btn btn-default"})
    @Html.ActionLink(@Resources.Content.AddAdvert, "Create", null, new { @Class = "btn btn-default"})
</p,>

    <table class="styled-table">

        <colgroup>
            <col span="1" style="width: 20%;">
            <col span="1" style="width: 60%;">
            <col span="1" style="width: 15%;">
            <col span="1" style="width: 10%;">
            <col span="1" style="width: 5%;">
        </colgroup>


        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.User.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Content)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>


        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.Email)
                </td>
                <td>
                    @Html.Raw(item.Content)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td style="vertical-align:middle">
                    @Html.ActionLink(@Resources.Content.Edit, "Edit", new { id = item.ID }) <br>
                    @Html.ActionLink(@Resources.Content.Details, "Details", new { id = item.ID })<br>
                    @Html.ActionLink(@Resources.Content.Delete, "Delete", new { id = item.ID })
                </td>
                <td style="text-align: center; vertical-align:middle">
                    @{
                        var app = (HttpApplicationStateWrapper)ViewData["app"];
                        if (app[item.ID.ToString()] != null)
                        {
                            <div>@app[item.ID.ToString()]</div>
                        }
                        else
                        {
                            <div>0</div>
                        }
                    }

                </td>
            </tr>
        }

    </table>